### PR TITLE
Naming

### PR DESCRIPTION
**Pull request by segunjkf**

### CODE REVIEW

**Review by geoffrey1330 — COMMENTED** [review]
rename the variable from  `"Env_code"` to all lower case `"env_code"`

**Comment by segunjkf** [comment]
> rename the variable from `"Env_code"` to all lower case `"env_code"`

i have made the changes

**Comment by geoffrey1330** [comment]
The variable renaming was done properly Good job. 
but I saw a new folder **other-vpc** could you please explain to me what the folder is for?

**Comment by segunjkf** [comment]
> The varaible renaming was done properly Good job. but I saw a new folder **other-vpc** could you please explain to me what the folder is for?

When I was going through the video I noticed two vpcs were created for better understanding of  the variable function in Terraform. That's why I created another VPC.

**Comment by geoffrey1330** [comment]
> > The varaible renaming was done properly Good job. but I saw a new folder **other-vpc** could you please explain to me what the folder is for?
> 
> When I was going through the video I noticed two vpcs were created for better understanding of the variable function in Terraform. That's why I created another VPC.

Could you please remove the folder and make you new commit for review, if you have properly understood variable function in Terraform?

**Comment by segunjkf** [comment]
> > > The varaible renaming was done properly Good job. but I saw a new folder **other-vpc** could you please explain to me what the folder is for?
> > 
> > 
> > When I was going through the video I noticed two vpcs were created for better understanding of the variable function in Terraform. That's why I created another VPC.
> 
> Could you please remove the folder and make you new commit for review, if you have properly understood variable function in Terraform?

Done you can review now

**Review by geoffrey1330 — APPROVED** [review]

**Pull request merged**
